# Where things are
source: .
destination: ./_site
plugins: ./_plugins
layouts: ./_layouts
data_source: ./_data
collections: null

# Handling Reading
safe: false
include: [".htaccess"]
exclude: []
keep_files: [".git", ".svn"]
encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
textile_ext: "textile"

# Serving
detach: false
port: 4000
host: 127.0.0.1
baseurl: ""
# does not include hostname



# Dependencies
markdown:         redcarpet
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
title:            前端扯淡
tagline:          'A Jekyll theme'
description:      '我是小学生'
url:              https://zhea55.github.io

author:
  name:           'zhea55'
  url:            https://zhea55.github.io

paginate:         5

# Custom vars
version:          2.0.0

github:
  repo:           https://zhea55.github.io

gems: [rouge, mini_magick]

# Picture
picture:
  source: public/images/_fullsize
  output: generated
  markup: picture
  presets:
    # Full width pictures
    default:
      ppi: [1, 1.5]
      attr:
        class: blog-full
        itemprop: image
      source_lrg:
        media: "(min-width: 40em)"
        width: 720
      source_med:
        media: "(min-width: 30em)"
        width: 450
      source_default:
        width: 350
    # Half width pictures
    half:
      ppi: [1, 1.5]
      attr:
        data-location: "{{location}}"
        data-active: nil
      source_lrg:
        media: "(min-width: 40em)"
        width: 400
      source_med:
        media: "(min-width: 30em)"
        width: 250
      source_default:
        width: 350
    # Self-set resolution sources. Useful if you don't want a 1:1 image size to dppx ratio.
    gallery:
      source_wide_hi:
        media: "(min-width: 40em) and (min-resolution: 1.5dppx)"
        width: 900
        height: 600
      source_wide:
        media: "(min-width: 40em)"
        width: 600
        height: 400
      source_default:
        width: 250
        height: 250
